### ISSUE TITLE
Add new tenant in BC2ADLS_EnvironmentHub

### ISSUE THREAD

**Issue by BastiaanVoort** [Bertverbeek4PS/bc2adls_EnvironmentHub#1]
Hi Bert,

Upon adding a new tenant in the BC2ADLS Environment Hub, the tables and columns configured in the BC2ADLS extension do not get synchronized with this new tenant. 

It is not feasible for us to manually select and deselect over 200+ BC tables along with their corresponding columns to facilitate synchronization with the new tenant. 

![image](https://github.com/Bertverbeek4PS/bc2adls_EnvironmentHub/assets/142785343/ca0cdfdf-afbc-4274-beeb-12a827ff8815)

We would appreciate a more suitable solution to address this issue.

**Comment by Bertverbeek4PS** [comment]
@BastiaanVoort I can only think about an export and import of the schema in bc2adls.
In that case you can just simply import everything.
After that is done it will export everything when you push the export button.

**Comment by Bertverbeek4PS** [comment]
@BastiaanVoort with https://github.com/Bertverbeek4PS/bc2adls/pull/83 it is now possible to export and import the tables and fields.
