### ISSUE TITLE
Enable, disable or add new administration in BC2ADLS_EnvironmentHub

### ISSUE THREAD

**Issue by BastiaanVoort** [Bertverbeek4PS/bc2adls_EnvironmentHub#2]
Hi Bert,

When we add a new BC administration in the BC2ADLS Environment Hub, the Schedule Export is not synchronized with this new BC administration. The work-around of deleting all schedule jobs and then synchronizing a new schedule job for all 600+ BC administrations results in a significant amount of message traffic.

![image](https://github.com/Bertverbeek4PS/bc2adls_EnvironmentHub/assets/142785343/67b3f10f-b659-4a03-b9f1-9c151b74078b)

Also importent: when we disable or remove BC administration from the BC2ADLS Environment Hub, the Schedule Export for that specific BC administration should be deleted.
![image](https://github.com/Bertverbeek4PS/bc2adls_EnvironmentHub/assets/142785343/7a8004c2-5ad7-4a16-ab92-256e254cb643)

We would appreciate a more suitable solution to address this issue.

**Comment by Bertverbeek4PS** [comment]
@BastiaanVoort 
Maybe we can add a selection of a company to add or delete an schedule.
In that case you can choose one company for this.

**Comment by Bertverbeek4PS** [comment]
@BastiaanVoort you can now choose an environment in this commit:
https://github.com/Bertverbeek4PS/bc2adls_EnvironmentHub/commit/958176481d2a9b47ca90e0b909ef763d70f2b99c
